# Generated by Django 2.1.4 on 2019-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128, unique=True, verbose_name='用户 login')),
                ('nickname', models.CharField(max_length=128, verbose_name='昵称')),
            ],
        ),
    ]
