# Generated by Django 2.1.4 on 2019-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drafters',
            field=models.ManyToManyField(related_name='drafters', to='glaw.User', verbose_name='定稿人'),
        ),
        migrations.AlterField(
            model_name='post',
            name='proofreaders',
            field=models.ManyToManyField(related_name='proofreaders', to='glaw.User', verbose_name='校对者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='glaw.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='post',
            name='translators',
            field=models.ManyToManyField(related_name='translators', to='glaw.User', verbose_name='译者'),
        ),
    ]
