# Generated by Django 2.1.4 on 2019-01-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaw', '0005_auto_20190107_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='译文发布时间'),
        ),
    ]
